"""
Django settings for AnsibleMster project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y03ezr@ztgks60&fp__g6c4zb(@c)$hhmp$vb-07)3*4tq8hsy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AnsibleMaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'apps/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AnsibleMaster.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 数据库配置 用于首次启动
DATABASES = {
    'default': {
        # 暂时采用mysql数据库
        'ENGINE': 'django.db.backends.mysql',
            "OPTIONS": {
                # "read_default_file": "../AnsibleMaster/my.cnf",
                'read_default_file': str(BASE_DIR / "AnsibleMaster/my.cnf"),
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",  # 示例额外配置
        },
    }
}
# DATABASES = {
#     'default': {
#         # 暂时采用mysql数据库
#         # 'ENGINE': 'django.db.backends.sqlite3',
#         # 'NAME': BASE_DIR / 'db.sqlite3',
#         # 数据库引擎
#         'ENGINE': 'django.db.backends.mysql',
#         # 数据库名
#         'NAME': 'AnsibleMaster',
#          # 数据库用户名
#         'USER': '',
#         # 数据库地址
#         'HOST': '',
#         # 数据库端口
#         'PORT': '3306',
#         # 数据库密码
#         'PASSWORD': '',
#     }
# }

# 如果存在配置文件，覆盖默认
# CONFIG_FILE = BASE_DIR / 'config.json'
# if CONFIG_FILE.exists():
#     try:
#         with open(CONFIG_FILE) as f:
#             config = json.load(f)
#         # 使用get方法，避免KeyError，并提供默认值
#         DATABASES['default'].update({
#             'NAME': config.get('DB_NAME', 'AnsibleMaster'),
#             'USER': config.get('DB_USER', ''),
#             'HOST': config.get('DB_HOST', ''),
#             'PORT': config.get('DB_PORT', '3306'),
#             'PASSWORD': config.get('DB_PASSWORD', ''),
#         })
#     except Exception as e:
#         print(f"加载配置文件失败: {e}")

SESSION_COOKIE_AGE = 1209600  # 两周（记住我功能）
SESSION_SAVE_EVERY_REQUEST = True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "apps/static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
